List<String> AOLText = [
  "ABOUT US",
  'We serve the society by helping the needy people',
  'Operating in 156 countries, The Art of Living is a non-profit, educational and humanitarian organization founded in 1981 by the world-renowned humanitarian and spiritual teacher - Gurudev Sri Sri Ravi Shankar. All our programs are guided by Gurudev’s philosophy: “Unless we have a stress-free mind and a violence-free society, we cannot achieve world peace.”',
  'The Art of Living community is diverse and \nattracts people from all walks of life.',
  '39\nyears of service',
  '156\ncountries where we make\na difference',
  '10,000+\ncenters worldwide with \nweekly follow-up sessions',
  '450 million\nlives touched',
  "Founder",
  "Sri Sri Ravi Shankar Ji",
  'Gurudev Sri Sri Ravi Shankar has united people of different races, traditions, economic and social status, and nationalities.This community, spanning 156 countries, has created a one-world spiritual family.',
  'Gurudev’s message is simple: “Love and wisdom can prevail over hatred and violence.” This message is not just a slogan, but through The Art of Living has been and continues to be translated into action and results.',
  'Contact Us',
  'India Office',
  'Phone: +91 8067612345',
  'Fax: +91 8028432833',
  'Email: secretariat@artofliving.org',
  'Address: Office of gurudev Sri Sri Ravi Shankar,The Art of living International centre',
  'Feedback',
  'Home page',
];
