List<String> workerText = [
  'Welcome',
  'Projects',
  'Team',
  'Statistics',
  "Completed",
  "Ongoing",
  "Not Started",
  "Update Your Work",
  'Dashboard',
  'Approve Work',
  'Get Report',
  'Update',
  'Approvals',
  'Update Your Work',
  'No data found',
  'Status: ',
  'Hours Worked: ',
  'Length: ',
  'Depth: ',
  'Lower width: ',
  'Upper width: ',
  'Volume Excavated: ',
  'Comment: ',
  'No Error Dectected',
  'Example App',
  "All Photos",
  'Please add machines',
  "Please enter positive time interval",
  'Added successfully',
  'Failed. Check your Internet',
  'For :',
  'Select any',
];


List<String> workerText2 = [
  'Done',
  'Hours Worked',
  'Digging Dimensions',
  'Please enter Length',
  "Length ",
  "Enter LengthController",
  "Please Enter Depth",
  "Depth",
  'Enter Depth',
  'Please Enter Upper Width',
  'Upper Width',
  'Enter Upper Width',
  'Please Enter Lower Width',
  'Lower Width',
  'Enter Lower Width',
  'No comment',
  '(Optional) Comment',
  'Upload Photos',
  'Pick images',
  'Work Already Submitted',
  'Submit',
  'BREAK',
  'START',
  'END',
  'Error',
  "Worker",
  ' Our Resources',
  "Our Petrol Pump",
  'Our Machines',
  'Our Projects',
  'No project assigned',
];

List<String> superText = [
  'Dashboard',
  'Error',
  'Our Resources',
  'Our Petrol Pumps',
  "Our Machines",
  "Our Projects",
  "Your Allocated Projects",
  "Create/Accept Workers",
  'My Documents',
  'Shared With Me',
  'Our Project',
  'Project Name',
  'Duration',
  ' days',
  'Excavation',
  'Status',
  'Goals',
  'Site Address',
  'Machines Provided',
  'Name:  ',
  'Usage/day:  ',
  'Our Supervisors',
  'Our Workers',
  'Images',
  'Report is generated on ',
  "Project name: ",
  'Site Address: ',
  "Soil Type: ",
  'Excavation Goals: ',
  'Estimated Duration: ',
  ' days',
];

List<String> superText2 = [
  'Estimated Rent: ',
  ' rs',
  'Estimated Fuel : ',
  ' litre',
  "Completion Percent: ",
  "Approved Excavation: ",
  "Project Supervisors Details: ",
  "Name",
  'Contact no',
  'Work Details of ',
  'Approved Excavation: ',
  'Worker Name',
  'Hours Worked',
  'Machine used',
  'Volume Excavated',
  'Approval Status',
  'Work is not yet started\n Hence report cannot be generated',
  'Project Completion',
  'Machines',
  'Workers',
  'Project Details',
  'Add Workers',
  'Approve Work',
  'Project Report',
  'No project assigned',
  "Project assigned",
  'No project assigned',
  "Added successfully",
  'Failed. Check your Internet',
  'Add Workers',
  'Select any',
];

List<String> superText3 = [
  'Save without selection',
  'Save',
  'Declined successfully',
  'Name: ',
  "Email :",
  "Sign In method : OTP",
  "Address: ",
  "Age: ",
  'Phone no: ',
  'Accept',
  'Decline',
  'Worker Request List',
  'No request found',
  'Added successfully',
  'Failed. Check your Internet !',
  'Email',
  'Enter Email',
  'Enter a valid email address',
  'Make worker form',
  'Sign In Method',
  'Email ID',
  'OTP',
  'Enter your Name',
  'Enter Phone Number',
  'Enter a valid Phone Number',
  "Enter your Address",
  'Enter your Age',
  "Create Worker",
  'Create',
  'Accept',
];

List<String> superText4 = [
  'Approve',
  'Update Work',
  'Approve Work',
  'No request found',
  "Work Details:",
  "Worker Name: ",
  "Volume Excavated: ",
  "Hours Worked: ",
  'Length: ',
  'Depth: ',
  'Upper Width: ',
  'Lower Width: ',
  'Work difference: ',
  'Approval status: ',
  'Images: ',
  'Approve',
  'Already Accepted',
  'Reject',
  'Already Declined',
  'No Error Dectected',
  'Added successfully',
  'Failed. Check your Internet',
  'Update For Workers',
  'For :',
  'Select one',
  "Hours Worked",
  'Digging Dimensions',
  "Length ",
  'Enter Length Controller',
  'Please Enter Depth',
  'Depth',
];

List<String> superText5 = [
  'Enter Depth',
  'Please Enter Upper Width',
  'Upper Width',
  'Enter Upper Width',
  "Please Enter Lower Width",
  "Lower Width",
  "Enter Lower Width",
  "No comment",
  '(Optional) Comment',
  'Upload Photos',
  'Pick images',
  'Work Already Submitted',
  'Submit',
  'BREAK',
  'START',
  'END',

];